# This configuration tells Railway how to build and deploy the project.
# It defines 4 separate services, one for each agent.
# The `-u` flag is added to the python command to ensure unbuffered output for real-time logging.

[build]
# All services will use the same Dockerfile to build the environment.
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
# This is a global deployment setting. Services will restart if they fail.
restartPolicyType = "ON_FAILURE"

# Define the first agent as a service.
[[services]]
name = "agent-1"
startCommand = "python -u main.py --agent-id 1"

# Define the second agent as a service.
[[services]]
name = "agent-2"
startCommand = "python -u main.py --agent-id 2"

# Define the third agent as a service.
[[services]]
name = "agent-3"
startCommand = "python -u main.py --agent-id 3"

# Define the fourth agent as a service.
[[services]]
name = "agent-4"
startCommand = "python -u main.py --agent-id 4"
